apiVersion: v1
kind: Service
metadata:
  name: eth-apache-service
  namespace: ethereum-ns
  labels:
    app: eth-apache-service
spec:
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: eht-geth-miner